export const top100Films = [
  { title: "The Shawshank Redemption", type: "random" },
  { title: "The Godfather", type: "email" },
  { title: "The Godfather: Part II", type: "email" },
  { title: "The Dark Knight", type: "email" },
  { title: "12 Angry Men", type: "email" },
  { title: "Schindler's List", type: "email" },
  { title: "Pulp Fiction", type: "email" },
  {
    title: "The Lord of the Rings: The Return of the King",
    type: "email",
  },
  { title: "The Good, the Bad and the Ugly", type: "email" },
  { title: "Fight Club", type: "email" },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    type: "email",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    type: "email",
  },
  { title: "Forrest Gump", type: "email" },
  { title: "Inception", type: "email" },
  {
    title: "The Lord of the Rings: The Two Towers",
    type: "email",
  },
  { title: "One Flew Over the Cuckoo's Nest", type: "email" },
  { title: "Goodfellas", type: "email" },
  { title: "The Matrix", type: "email" },
  { title: "Seven Samurai", type: "email" },
  {
    title: "Star Wars: Episode IV - A New Hope",
    type: "email",
  },
  { title: "City of God", type: "email" },
  { title: "Se7en", type: "email" },
  { title: "The Silence of the Lambs", type: "email" },
  { title: "It's a Wonderful Life", type: "email" },
  { title: "Life Is Beautiful", type: "contact" },
  { title: "The Usual Suspects", type: "contact" },
  { title: "Léon: The Professional", type: "contact" },
  { title: "Spirited Away", type: "contact" },
  { title: "Saving Private Ryan", type: "contact" },
  { title: "Once Upon a Time in the West", type: "contact" },
  { title: "American History X", type: "contact" },
  { title: "Interstellar", type: "contact" },
  { title: "Casablanca", type: "contact" },
  { title: "City Lights", type: "contact" },
  { title: "Psycho", type: "contact" },
  { title: "The Green Mile", type: "contact" },
  { title: "The Intouchables", type: "contact" },
  { title: "Modern Times", type: "contact" },
  { title: "Raiders of the Lost Ark", type: "contact" },
  { title: "Rear Window", type: "contact" },
  { title: "The Pianist", type: "contact" },
  { title: "The Departed", type: "contact" },
  { title: "Terminator 2: Judgment Day", type: "contact" },
  { title: "Back to the Future", type: "address" },
  { title: "Whiplash", type: "address" },
  { title: "Gladiator", type: "address" },
  { title: "Memento", type: "address" },
  { title: "The Prestige", type: "address" },
  { title: "The Lion King", type: "address" },
  { title: "Apocalypse Now", type: "address" },
  { title: "Alien", type: "address" },
  { title: "Sunset Boulevard", type: "address" },
  {
    title:
      "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    type: "address",
  },
  { title: "The Great Dictator", type: "address" },
  { title: "Cinema Paradiso", type: "address" },
  { title: "The Lives of Others", type: "address" },
  { title: "Grave of the Fireflies", type: "address" },
  { title: "Paths of Glory", type: "address" },
  { title: "Django Unchained", type: "address" },
  { title: "The Shining", type: "address" },
  { title: "WALL·E", type: "address" },
  { title: "American Beauty", type: "account-number" },
  { title: "The Dark Knight Rises", type: "account-number" },
  { title: "Princess Mononoke", type: "account-number" },
  { title: "Aliens", type: "account-number" },
  { title: "Oldboy", type: "account-number" },
  { title: "Once Upon a Time in America", type: "account-number" },
  { title: "Witness for the Prosecution", type: "account-number" },
  { title: "Das Boot", type: "account-number" },
  { title: "Citizen Kane", type: "account-number" },
  { title: "North by Northwest", type: "account-number" },
  { title: "Vertigo", type: "account-number" },
  {
    title: "Star Wars: Episode VI - Return of the Jedi",
    type: "account-number",
  },
  { title: "Reservoir Dogs", type: "account-number" },
  { title: "Braveheart", type: "account-number" },
  { title: "M", type: "account-number" },
  { title: "Requiem for a Dream", type: "account-number" },
  { title: "Amélie", type: "account-number" },
  { title: "A Clockwork Orange", type: "account-number" },
  { title: "Like Stars on Earth", type: "account-number" },
  { title: "Taxi Driver", type: "account-number" },
  { title: "Lawrence of Arabia", type: "random" },
  { title: "Double Indemnity", type: "random" },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    type: "random",
  },
  { title: "Amadeus", type: "random" },
  { title: "To Kill a Mockingbird", type: "random" },
  { title: "Toy Story 3", type: "random" },
  { title: "Logan", type: "random" },
  { title: "Full Metal Jacket", type: "random" },
  { title: "Dangal", type: "random" },
  { title: "The Sting", type: "random" },
  { title: "2001: A Space Odyssey", type: "random" },
  { title: "Singin' in the Rain", type: "random" },
  { title: "Toy Story", type: "random" },
  { title: "Bicycle Thieves", type: "random" },
  { title: "The Kid", type: "random" },
  { title: "Inglourious Basterds", type: "random" },
  { title: "Snatch", type: "random" },
  { title: "3 Idiots", type: "random" },
  { title: "Monty Python and the Holy Grail", type: "random" },
];
